#Configure the Server Port
server:
  port: 8010
  
spring:
  application:
   name: Student-SERVICE 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbdb
    username: root
    password: 18106047

